name: Lint, Test, Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout branch

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build
